apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.fullname" . }}-defect-dojo-api-credentials
  labels:
  {{- include "charts.labels" . | nindent 4 }}
data:
  apiKey: {{ required "defectDojoApiCredentials.apiKey is required" .Values.defectDojoApiCredentials.apiKey
    | b64enc | quote }}
  url: {{ required "defectDojoApiCredentials.url is required" .Values.defectDojoApiCredentials.url
    | b64enc | quote }}
type: Opaque